# Generated by Django 4.2 on 2025-04-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_rename_name_myuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
