# Generated by Django 4.2 on 2025-03-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_myuser_is_active_myuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user',
        ),
    ]
