# Generated by Django 4.2 on 2025-04-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_remove_myuser_username_myuser_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
