# Generated by Django 4.2 on 2025-04-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
